Repository AlaskaAirlines/auro-card, pull requests merged in 2021-03, with the labels that each got.

#4 fix(banner): prevent billboard form overflowing
  src/style-banner.scss
Labels: Status: Review Needed, Type: Bug

#5 fix: remove extra padding from banner in hero mode
  package-lock.json
  src/style-banner.scss
Labels: Type: Bug

#6 fix: unset overflow hidden on other variants
  src/style-banner.scss
Labels: Type: Bug

#8 auro-banner: content overflow issue
  package-lock.json
  src/style-banner.scss
Labels: Type: Bug

#10 feat: add rounded border variant for cc ads
  demo/banner-demo.md
  src/auro-banner.js
  src/style-banner.scss
Labels: Type: Feature

#12 fix: update marquee and roundedBorder per issues with responsive UI
  demo/banner-demo.md
  docs/api.md
  package-lock.json
  scripts/postCss.js
  src/style-banner.scss
Labels: Status: Complete and Ready to Merge, Status: Review Needed, Type: Bug

#13 fix: fix responsive banner
  demo/banner-demo.md
  package-lock.json
  src/style-banner.scss
Labels: Status: Complete and Ready to Merge, Type: Bug
